- llvm/include/llvm/MC/MCTargetOptions.h
- llvm/lib/Target/X86/X86FrameLowering.cpp
- llvm/tools/llc/llc.cpp
X86 uses a heuristic to order frame objects in `X86FrameLowering::orderFrameObjects`, but AArch64 does not have such implementation.
For now, we add a flag to optionally deactivate this (based on Marcus' suggestion). In the future, we might want to consider implementing a similar approach for AArch64, which shouldn't be that hard.
> [layout] Add flag for disabling X86 heuristic for frame object ordering.

- llvm/include/llvm/MC/MCTargetOptions.h
- llvm/lib/Target/AArch64/AArch64FrameLowering.cpp
- llvm/tools/llc/llc.cpp
We would like to be able to experiment with the CSR alignment in AArch64, which by default is 16. It seems that 8 is useful for getting the same layout with X86.
> Add parameter flag for setting the single CSR alignment in AArch64.

- llvm/lib/Target/X86/X86InstrSSE.td
In X86 MOVSDrm_alt is rematerializable, which means that it doesn't have to be spilled in memory.
Essentially, X86 uses rip-relative addressing to get the constant values of the global variables,
directly from the stack, whereas AArch64 loads the constant to a GPR, and then copies the GPR to the FPR.
So, we always treat MOVSS/MOVSD as not rematerializable, so X86 will be forced to also spill in the stack.
Fixes: 
https://github.com/systems-nuts/UnASL/issues/26
https://github.com/systems-nuts/UnASL/issues/34
See the last issue for more info.
> [layout] Convert MOVSS/MOVSD X86 instructions to not rematerializable.

- llvm/lib/Target/X86/X86InstrArithmetic.td
When we are accessing references inside a loop, X86 will usually use LEA
instructions that are hoisted outside of the loop. This causes greater
register pressure. The main problem, however, is that AArch64 will use
simple arithmetic instructions, which are usually rematerialized instead
of hoisted. To fix that difference, we set the `isAsCheapAsAMove` flag
for LEA64r, so that `simple-register-coalescing` will also rematerialize LEAs.
Moreover, this makes the flag `sink-insts-to-avoid-spills` unnecessary.
Closes:
https://github.com/systems-nuts/UnASL/issues/31
Also fixes in (probably) a better way:
https://github.com/systems-nuts/UnASL/issues/30
> [layout] Treat LEA64 x86 instructions as cheap as a move.

- llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
When the same SD constant is used in X86 by a store and a CopyToReg
as users, we want to reuse the same virtual register for this,
since this is what AArch64 does. Therefore, we try to match with
MOV32mr, so that the constant should come from a register.
Addresses: https://github.com/systems-nuts/UnASL/issues/76
Similar to: https://github.com/blackgeorge-boom/llvm-project/pull/14
> [layout] Use MOV32mr instead of MOV32ri with store and CopyToReg as users

- llvm/lib/Target/AArch64/AArch64.td
- llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
- llvm/lib/Target/AArch64/AArch64Subtarget.h
- llvm/lib/Target/X86/X86.td
- llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
- llvm/lib/Target/X86/X86Subtarget.h
We encode in instructions only immediates that can be represented
using 12 bits, with an optional bit to declare that the immediate
is a value shifted by 12. Otherwise, a register is used to hold larger
immediates. This is how AArch64 represents immediates.
We support this currently for instructions that are using constant
values in the DAG.
Fixes `create_seq` problem in https://github.com/systems-nuts/UnASL/issues/62.
> [layout] Immediates in instructions have the same size as in AArch64.

- llvm/lib/Target/AArch64/AArch64InstrInfo.td
Hoisting ADRP creates an arch-specific value in the case of AArch64,
whereas LEA instructions are not hoisted because of:
https://github.com/blackgeorge-boom/llvm-project/pull/13
In order to make the coalescer to bring ADRP back in the loop,
after licm, we need to do a similar change.
Addresses: https://github.com/systems-nuts/UnASL/issues/74
Eventually, we want to add this option with a TableGen flag, but I've not found a good way to give this through the command line in `isAsCheapAsAMove`.
> [layout] Do not hoist ADRP instruction out of loops.

- llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
- llvm/lib/Target/X86/X86InstrInfo.td
Addresses: https://github.com/systems-nuts/UnASL/issues/78
> [layout] Do not Use MOV32mr instead of MOV32ri, for the zero constant with store and CopyToReg as users.

- llvm/lib/Target/AArch64/AArch64.td
- llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
- llvm/lib/Target/AArch64/AArch64Subtarget.h
Only zero fp-immediates are materialized using `FMOVDi`-like
instructions, as in the case of X86.
Addresses: https://github.com/systems-nuts/UnASL/issues/81
> [layout] Add flag for disabling materializing of fp immediates in AArch64

- clang/lib/Basic/Targets/X86.h
- llvm/lib/Target/X86/X86TargetMachine.cpp
Addresses: https://github.com/systems-nuts/UnASL/issues/71
> [layout] Align one-byte sized stack objects to four bytes.

- llvm/lib/Target/X86/X86Values.cpp
So far, the code was not handling the case where the operand
was an immediate.
Addresses: https://github.com/systems-nuts/UnASL/issues/84
> [layout] Handle MOV32ri64 instructions with immediates in stacktransformmetadata pass.

- llvm/lib/Target/X86/X86.td
- llvm/lib/Target/X86/X86InstrArithmetic.td
- llvm/lib/Target/X86/X86InstrCompiler.td
- llvm/lib/Target/X86/X86InstrInfo.td
- llvm/lib/Target/X86/X86Subtarget.h
In the case of AArch64, there are no intsructions for multiplying
a register with immediate, thus an extra register is used to hold
the immediate. We emulate the same behavior for X86 by not generating
these kinds of instructions.
Use with `mattr=-multiply-with-imm`
Addresses: https://github.com/systems-nuts/UnASL/issues/86
> [layout] Do not encode immediates in multiplications for X86.

- llvm/lib/MC/MCObjectFileInfo.cpp
- llvm/lib/MC/MCSectionELF.cpp
The ELF sections added by the Popcorn compiler modifications trigger an assertion due to a missing ELF flag in the emitted section when producing human-readable assembly.
The affected ELF sections are:
- `.stack_transform.unwind`
- `.stack_transform.unwind_arange`
This patch:
- Adds the required `SHF_MERGE` flag in the aforementioned emitted ELF sections.
- Adds debug printing for this issue to increase visibility for potential future uses.
Addresses: https://github.com/systems-nuts/UnASL/issues/91
> [layout] Add required ELF flags when printing human-readable assembly

- llvm/lib/Target/AArch64/AArch64InstrInfo.td
This is different from 5b0b02933263da7d319079c3ba307aed758f26b1 .
The problem now is with passing globals by value, because AArch64
needs two instructions (`adrp`+`ldr`), and when `adrp` is hoisted
the coalescer cannot bring it back. So, now, we don't hoist
`adrp` at all.
In the other case, we had to sink back `MOVaddr`, which later
expands into `adrp`+`add`.
Addresses: https://github.com/systems-nuts/UnASL/issues/93
> [layout] Do not hoist the ADRP instruction.

- llvm/lib/Target/AArch64/AArch64.td
- llvm/lib/Target/AArch64/AArch64InstrFormats.td
- llvm/lib/Target/AArch64/AArch64InstrInfo.td
- llvm/lib/Target/AArch64/AArch64RegisterInfo.td
- llvm/lib/Target/AArch64/AArch64Subtarget.h
With consecutive calls of the same global argument (by value),
the compiler will use a CSR as the destination of the ADRP.
This register needs to be pushed, but X86 has rip-relative
mem-to-reg moves, which avoid this issue. So, we need to use
temporary registers in the case of AArch64.
@compor I didn't find a good way to add this change as a flag, so it's hardcoded for now, as the other older changes regarding the register classes modifications.
Addresses: https://github.com/systems-nuts/UnASL/issues/102
> [layout] Use only temporary registers for ADRP instructions (not coming from MOVaddr)

- llvm/lib/Target/X86/X86.td
- llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
- llvm/lib/Target/X86/X86InstrInfo.td
- llvm/lib/Target/X86/X86Subtarget.h
In the case of AArch64, these immediates need to be loaded into a
register first. Sometimes, a CSR will be used, which breaks the
unified address space with X86, which can move directly immediates
to memory. Add a flag to deactivate this X86 capability.
We may need to do the same for other immediate sizes.
Addresses: https://github.com/systems-nuts/UnASL/issues/104
> [layout] Do not move directly 32-bit immediates to memory in X86.

- llvm/lib/Target/AArch64/AArch64FrameLowering.cpp
- llvm/lib/Target/X86/X86FrameLowering.cpp
- llvm/lib/Target/X86/X86RegisterInfo.cpp
- llvm/lib/Target/X86/X86RegisterInfo.h
AArch64 tries to reserve an extra CSR during register scavenging,
in order to use it to access stack offsets larger than 255,
which cannot be encoded directly to instructions as an offset.
If the stack size is larger than 255, but AArch64 cannot find a CSR,
it will reserve a special spill slot for that purpose.
To align that behaviour with X86, we add a flag to always (conservatively)
assign this spill slot for both architectures.
Addresses: https://github.com/systems-nuts/UnASL/issues/110
> [layout] Add flag for reserving a register scavenging spill slot.

- llvm/lib/Target/X86/X86.td
- llvm/lib/Target/X86/X86ISelLowering.cpp
- llvm/lib/Target/X86/X86Subtarget.h
- llvm/lib/Target/X86/X86TargetTransformInfo.cpp
AArch64 and X86 follow a different strategy for materializing constants,
e.g., whether to encode the full constant, or encode a smaller one and
add the rest of the value as a separate instruction.
We want to align both architectures in this respect.
Addresses: https://github.com/systems-nuts/UnASL/issues/115
> [layout] Add X86 flag for following AArch64 constant cost model.

- llvm/lib/Target/X86/X86.td
- llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
- llvm/lib/Target/X86/X86Subtarget.h
We introduce an extra LEA instruction for computing the address,
instead of encoding things like [base + scaled register + offset] in
one command, to follow what AArch64 is doing in register offset addressing.
Addresses: https://github.com/systems-nuts/UnASL/issues/117
> [layout] Add flag for simplified addressing in the case of register offset in X86.

- llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
We add a more specific check for the case that solves:
042f2f81e548e07c2bf4199c61117d6dfcd5cfcd
From now on, we will check if at least one of the operands of the add
node in the DAG are of SHL type, which probably means that we are
in the case of addressing with scaled-register offset.
Otherwise, the previous solution was introducing assymetries for
other addressing mode cases.
Addresses: https://github.com/systems-nuts/UnASL/issues/129
> [layout] Make check for simplified addressing with register offset SHL-specific

- llvm/lib/Target/X86/X86InstrCompiler.td
- llvm/lib/Target/X86/X86RegisterInfo.td
There are cases where X86 reuses the zero constant, consuming
callee-saved registers. But, AArch64 has a dedicated wzr register,
so it doesn't need to do the same. We remove CSR registers from the
pool of MOV32r0 to solve this issue. In the future, we would like
to add this option as a flag.
Addresses: https://github.com/systems-nuts/UnASL/issues/134
> [layout] Use only temp registers for X86::MOV32r0.

- llvm/lib/Target/X86/X86.td
- llvm/lib/Target/X86/X86ISelLowering.cpp
- llvm/lib/Target/X86/X86Subtarget.h
The constants are of the form 2^N+2/4/8.
Addresses: https://github.com/systems-nuts/UnASL/issues/151
> [layout] Avoid optimizing multiplication with specific constants in X86.

- llvm/lib/Target/X86/X86RegisterInfo.td
This leads to a more predictable register allocation.
Addresses: https://github.com/systems-nuts/UnASL/issues/152
> [layout] Assign zero cost per use for r15 and its subregisters.

- llvm/lib/CodeGen/StackTransformMetadata.cpp
- llvm/lib/Target/X86/X86Values.cpp
- llvm/lib/Target/X86/X86Values.h
So far, architecture-specific values that are stored in the stack
were not included in the stackmap section of the ELF binary.
For example, when the value of a global constant was spilled,
we weren't including this liveness information in the stackmaps.
Thus, our tools could not detect whether this live value would end
up in the same stack location.
This patch introduces support for these stack slots and also handles
X86 values generated by rip-relative memory-to-register operations,
with `MOVSDrm_alt`.
Addresses: https://github.com/systems-nuts/UnASL/issues/87
Addresses: https://github.com/systems-nuts/UnASL/issues/88
> [layout] Handle architecture-specific stack slots in stackmaps.

- llvm/lib/Target/AArch64/AArch64.td
- llvm/lib/Target/AArch64/AArch64InstrInfo.td
- llvm/lib/Target/AArch64/AArch64Subtarget.h
AArch64 supports instructions where the source operands are 32-bit,
whereas the destination is 64-bit. In X86, all operands will be 64-bit,
for a 64-bit destination, which leads to differences in register allocation,
in case there is a register used both as 32-bit and as 64-bit:
In X86 only one register will be used for that,
whereas AArch64 will employ one 32-bit and one 64-bit register.
Addresses: https://github.com/systems-nuts/UnASL/issues/179
> [layout] Avoid wide multiplication-addition instructions in AArch64.

- llvm/CMakeLists.txt
- llvm/cmake/modules/TableGen.cmake
- llvm/lib/Target/AArch64/AArch64.td
- llvm/lib/Target/AArch64/AArch64CallingConvention.td
- llvm/lib/Target/AArch64/AArch64InstrFormats.td
- llvm/lib/Target/AArch64/AArch64InstrInfo.td
- llvm/lib/Target/AArch64/AArch64RegisterInfo.td
- llvm/lib/Target/X86/X86CallingConv.td
- llvm/lib/Target/X86/X86InstrArithmetic.td
- llvm/lib/Target/X86/X86InstrCompiler.td
- llvm/lib/Target/X86/X86InstrSSE.td
- llvm/lib/Target/X86/X86RegisterInfo.td
This PR showcases:
- Addition of entry point CMake flag to inject Unifico-specific options (in our case we are interested in macros)
This is mostly a draft to test that we can actually use this facility relating to https://github.com/systems-nuts/unifico/issues/60
The interesting part is that it is not used anywhere in LLVM 9 except for TableGen's unit tests.
A few things to consider are:
- What kind of macro groups do we want (i.e., feature sets)?
- Changing those flags in CMake once the project has been configured requires invalidating its cache (`CMakeCache.txt`).  
The TableGen invocations are already set during configuration in the build tool's configuration (i.e., the one that CMake generates), such as `ninja`.
- TableGen invocations can also happen per project; not sure we want …
> Add flags for tablegen changes

- llvm/include/llvm/CodeGen/TargetRegisterInfo.h
- llvm/lib/CodeGen/RegisterCoalescer.cpp
- llvm/lib/CodeGen/SelectionDAG/InstrEmitter.cpp
- llvm/lib/Target/AArch64/AArch64.td
- llvm/lib/Target/AArch64/AArch64RegisterInfo.cpp
- llvm/lib/Target/AArch64/AArch64RegisterInfo.h
- llvm/lib/Target/AArch64/AArch64Subtarget.h
This extends https://github.com/blackgeorge-boom/llvm-project/pull/51, by adding the `copy-wzr-temp` AArch64 subtarget flag, in order to conditionally enable the functionality introduced by that PR.
> [layout] Add flag to control copying WZR to temp registers

- llvm/lib/CodeGen/StackTransformMetadata.cpp
When we are adding arch-specific stack slots, we need to use `sanitizeVRegs` after we create a value, not before. Otherwise, we will not check correctly if a virtual register has not been handled by the stackmap and when we will try to lower the register as part of the arch-specific value, we will fail.
Addresses: https://github.com/systems-nuts/unifico/issues/275
> [layout] Fix order of checking VRs after arch-specific value creation

- llvm/lib/Target/AArch64/AArch64RegisterInfo.td
- llvm/lib/Target/X86/X86RegisterInfo.td
Some of the X86 registers have higher use costs in register allocation. Instead of altering those costs, as we did in:
https://github.com/blackgeorge-boom/llvm-project/pull/41
it's better to assign these costs in the reciprocal AArch64 registers. So, we also undo the changes of the aforementioned PR.
Also, this PR fixes the allocation order of AArch64 GPRs, to be the same as the X86 one. This is fixed by defining the registers in the right order in the target description file.
Finally, this PR does a minor cleanup in the current definitions of the AArch64 file. Specifically, it removes unnecessary alternative GPR definition orders.
> AArch64 GPR Register Costs and Allocation Order

- llvm/lib/CodeGen/StackSlotColoring.cpp
This happens inside the stack-slot-coloring pass. For some reason, there are cases where our `-align-bytes-to-four` flag does not work, for example when lowering instructions that use `ccond`, which uses 32 bits in AArch64 and 8 bits in X86. We add an extra flag to hard-code that all stack objects should be aligned at a four-byte boundary at least.
Addresses: https://github.com/systems-nuts/unifico/issues/279
> Force alignment of all objects in the stack to be at least four bytes

- llvm/lib/Target/AArch64/AArch64InstrFormats.td
- llvm/lib/Target/AArch64/AArch64InstrInfo.cpp
- llvm/lib/Target/AArch64/AArch64InstrInfo.h
- llvm/lib/Target/X86/X86InstrInfo.cpp
When the two-address instruction pass is enabled, the ADD/SUB-rr instructions of AArch64 can now be converted to the tow-address format. This also requires support for converting them back to the three-address format, in the cases where X86 would do the same by converting these instructions into LEAs. Essentially, for AArch64 this just means that the instruction is copied back to its original three-address format.
Additionally, this patch introduces a small fix that uses `LEA32r` instead of `LEA64_32r` for the case of additions in X86.
Requires compiling with the `-DUNIFICO_TWO_ADDR` directive, along with the existing llc flag `enable-lea32`.
Addresses: https://github.com/systems-nuts/unifico/issues/283
> Convert AArch64 ADD/SUB-rr instructions to the two-address format

- llvm/lib/Target/X86/X86.td
- llvm/lib/Target/X86/X86ISelLowering.cpp
- llvm/lib/Target/X86/X86Subtarget.h
When `FSETCC` is lowered, a series of `FAND`, FANDN`, and `FOR` are generated. These make use of `v2f64` types, so X86 ends up spilling an SIMD `xxm` register. AArch64 on the other hand just generates `CMP` nodes, which end up using only one fp register.
We add an optional flag to disable this.
Addresses: https://github.com/systems-nuts/unifico/issues/284
> [layout][X86] Do not convert SELECT to FSETCC

- llvm/include/llvm/CodeGen/TargetRegisterInfo.h
- llvm/lib/CodeGen/RegisterCoalescer.cpp
- llvm/lib/Target/AArch64/AArch64RegisterInfo.cpp
- llvm/lib/Target/AArch64/AArch64RegisterInfo.h
When we are coalescing a temp register class, instead of blindly propagating the temporary class, we need to check whether the destination is a subregister. In this case, we may need to expand the temp register class, so that it fits the size of the destination class being subregistered.
Addresses: https://github.com/systems-nuts/unifico/issues/286
> [layout] Fix bug when coalescing temp regs to a subreg
